import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:5173/');
    await page.getByRole('link', { name: 'Log in' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('finance-manager@example.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('password');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await expect(page.locator('h1')).toContainText('Finance Manager Manager');
    await page.getByText('Open module').first().click();
    await page.getByRole('button', { name: 'Contracts' }).click();
    await page.getByRole('button').nth(4).click();
    await page.getByRole('textbox', { name: 'e.g. Globe Telecom' }).click();
    await page.getByRole('textbox', { name: 'e.g. Globe Telecom' }).fill('testing');
    await page.getByRole('combobox').first().selectOption('Service Agreement');
    await page.getByRole('textbox', { name: 'e.g. ITM-' }).click();
    await page.getByRole('textbox', { name: 'e.g. ITM-' }).fill('itm-0041');
    await page.getByRole('textbox', { name: 'e.g. Network Infrastructure' }).click();
    await page.getByRole('textbox', { name: 'e.g. Network Infrastructure' }).fill('network infrastructure');
    await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).click();
    await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).fill('sn-2026-001');
    await page.getByRole('textbox', { name: 'e.g. SBU-' }).click();
    await page.getByRole('textbox', { name: 'e.g. SBU-' }).fill('sbu-2026');
    await page.getByRole('combobox').nth(1).selectOption('Visayas');
    await page.locator('input[type="date"]').first().fill('2026-06-14');
    await page.locator('input[type="date"]').nth(1).fill('2032-12-14');
    await page.getByRole('button', { name: 'Create Contract' }).click();
    await page.getByRole('button', { name: 'Edit Contract' }).click();
    await page.getByRole('textbox', { name: 'e.g. Globe Telecom' }).click();
    await page.getByRole('textbox', { name: 'e.g. Globe Telecom' }).fill('testing testing');
    await page.getByRole('button', { name: 'Save Changes' }).click();
    await expect(page.locator('h1')).toContainText('testing testing');
    await page.getByRole('button').nth(3).click();
    await page.locator('div').filter({ hasText: /^Logout$/ }).nth(1).click();
    await page.getByRole('link', { name: 'Log in' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('finance-admin@example.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('password');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await expect(page.locator('h1')).toContainText('Finance Administrator Admin');
    await page.getByText('Open module').first().click();
    await page.getByRole('link', { name: 'Business & Suppliers' }).click();
    await page.locator('#add-partner-btn').click();
    await page.getByRole('textbox', { name: 'Organization name' }).click();
    await page.getByRole('textbox', { name: 'Organization name' }).fill('testing company');
    await page.getByRole('textbox', { name: 'e.g. Healthcare' }).click();
    await page.getByRole('textbox', { name: 'e.g. Healthcare' }).fill('healthcare');
    await page.getByRole('combobox').first().selectOption('Luzon');
    await page.getByRole('textbox', { name: 'Full name' }).click();
    await page.getByRole('textbox', { name: 'Full name' }).fill('test person');
    await page.getByRole('textbox', { name: '09xxxxxxxxx' }).click();
    await page.getByRole('textbox', { name: '09xxxxxxxxx' }).fill('09914159183');
    await page.getByText('Contact DetailsContact Person').click();
    await page.getByRole('textbox', { name: 'contact@company.com' }).click();
    await page.getByRole('textbox', { name: 'contact@company.com' }).click();
    await page.getByRole('textbox', { name: 'contact@company.com' }).fill('test@example.com');
    await page.getByRole('textbox', { name: 'Street, City' }).click();
    await page.getByRole('textbox', { name: 'Street, City' }).fill('test city');
    await page.getByRole('button', { name: 'Add Partner' }).click();
    await expect(page.getByRole('button', { name: 'Active testing company' })).toBeVisible({ timeout: 20000 });
    await page.locator('#reka-dropdown-menu-trigger-v-4').click();
    await page.getByRole('menuitem', { name: 'View details' }).click();
    await page.getByRole('button', { name: 'Edit' }).click();
    await page.getByRole('textbox', { name: 'Organization name' }).click();
    await page.getByRole('textbox', { name: 'Organization name' }).click();
    await page.getByRole('textbox', { name: 'Organization name' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Organization name' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Organization name' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Organization name' }).press('ArrowLeft');
    await page.getByRole('textbox', { name: 'Organization name' }).press('ArrowRight');
    await page.getByRole('textbox', { name: 'Organization name' }).fill('testing testing company');
    await page.getByRole('button', { name: 'Save Changes' }).click();
    await expect(page.locator('h1')).toContainText('testing testing company');
    await page.getByRole('button', { name: 'Back to Partners' }).click();
    await page.locator('#reka-dropdown-menu-trigger-v-6').click();
    await page.getByRole('menuitem', { name: 'Delete' }).click();
    await page.getByRole('button', { name: 'Delete' }).click();
    await page.getByRole('link', { name: 'Contracts' }).click();
    const contractRow = page.getByRole('row').filter({ hasText: 'testing testing' });
    await contractRow.waitFor({ timeout: 10000 });
    await contractRow.hover();
    await contractRow.getByRole('button').click();

    await page.getByRole('menuitem', { name: 'Delete' }).click();
    await expect(page.getByText('Contract removed')).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('Contract removed')).toBeVisible({ timeout: 10000 });

    await page.locator('div').filter({ hasText: /^Logout$/ }).nth(1).click();
});