import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome Back!' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).fill('finance-manager@example.com');
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await expect(page.getByRole('heading', { name: 'Finance Manager Finance' })).toBeVisible();
  await page.getByText('Contract ManagementTrack,').click();
  await expect(page.getByRole('heading', { name: 'Good evening, Finance.' })).toBeVisible();
  await page.getByRole('button', { name: 'Contracts' }).click();
  await expect(page.getByRole('heading', { name: 'All Contracts', exact: true })).toBeVisible();
  await page.getByRole('button').nth(4).click();
  await expect(page.getByRole('heading', { name: 'Create New Contract' })).toBeVisible();
  await page.getByRole('textbox', { name: 'e.g. Globe Telecom' }).click();
  await page.getByRole('button', { name: 'test', exact: true }).click();
  await page.getByRole('combobox').first().selectOption('Service Agreement');
  await page.getByRole('textbox', { name: 'e.g. ITM-' }).click();
  await page.getByRole('textbox', { name: 'e.g. ITM-' }).fill('6');
  await page.getByRole('textbox', { name: 'e.g. Network Infrastructure' }).click();
  await page.getByRole('textbox', { name: 'e.g. Network Infrastructure' }).fill('67');
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).click();
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).fill('7');
  await page.getByRole('textbox', { name: 'e.g. SBU-' }).click();
  await page.getByRole('textbox', { name: 'e.g. SBU-' }).fill('6767');
  await page.getByRole('combobox').nth(1).selectOption('Luzon');
  await page.locator('input[type="date"]').first().fill('2026-06-12');
  await page.locator('input[type="date"]').nth(1).fill('2028-06-12');
  await page.getByRole('button', { name: 'Create Contract' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('menuitem', { name: 'Edit contract' }).click();
  await page.getByRole('textbox', { name: 'e.g. Network Infrastructure' }).click();
  await page.getByRole('textbox', { name: 'e.g. ITM-' }).click();
  await page.getByRole('textbox', { name: 'e.g. ITM-' }).fill('67');
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).click();
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).click();
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'e.g. SN-2024-' }).fill('67');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await expect(page.getByText('Contract updated')).toBeVisible();
  await expect(page.getByText('67').first()).toBeVisible();
  await expect(page.getByText('67').nth(2)).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('FMFinance ManagerFinance').click();
  await page.getByRole('button', { name: 'Logout' }).click();
});