<?php

namespace App\Services\Ocr;

use App\Services\RiskAssessment\DocumentTextExtractor;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Process;

class OcrTextExtractor
{
    protected DocumentTextExtractor $nativeExtractor;

    public function __construct(DocumentTextExtractor $nativeExtractor)
    {
        $this->nativeExtractor = $nativeExtractor;
    }

    /**
     * Extract text from raw file bytes.
     *
     * @param string $fileBytes Raw file contents
     * @param string $fileName Original file name (e.g. "contract.pdf")
     * @param string $fileType Detected extension or MIME type suffix (e.g. "pdf", "docx", "png")
     * @return string|null The extracted text, or null on failure
     */
    public function extract(string $fileBytes, string $fileName, string $fileType): ?string
    {
        $fileType = strtolower(trim($fileType));

        return match ($fileType) {
            'docx' => $this->nativeExtractor->extract($fileBytes, 'docx'),
            'pdf' => $this->extractPdf($fileBytes),
            'png', 'jpg', 'jpeg', 'tiff', 'bmp', 'gif' => $this->extractImage($fileBytes, $fileType),
            default => $this->extractFallback($fileBytes, $fileName),
        };
    }

    /**
     * Extracts text from PDF.
     * Attempts native extraction first; falls back to OCR if little/no text is found.
     */
    protected function extractPdf(string $fileBytes): ?string
    {
        // 1. Try native text extraction first (e.g., text-layer PDFs)
        $nativeText = $this->nativeExtractor->extract($fileBytes, 'pdf');
        if ($nativeText && strlen(trim($nativeText)) > 100) {
            Log::info('Extracted native text from PDF (bypassing OCR)');
            return $nativeText;
        }

        Log::info('Native PDF text extraction yielded insufficient text. Falling back to Tesseract OCR.');

        // 2. Fall back to OCR: Convert PDF to images, then OCR each image
        $tempPdf = tempnam(sys_get_temp_dir(), 'ocr_pdf_');
        $pdfPath = $tempPdf . '.pdf';
        
        $tempDir = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'ocr_pages_' . uniqid();
        $outputPrefix = $tempDir . DIRECTORY_SEPARATOR . 'page';

        try {
            // Write PDF bytes
            file_put_contents($pdfPath, $fileBytes);
            
            // Create temp directory for page images
            if (!is_dir($tempDir)) {
                mkdir($tempDir, 0777, true);
            }

            // Run pdftoppm to extract pages as PNGs at 150 DPI
            $ppmResult = Process::run(['pdftoppm', '-png', '-r', '150', $pdfPath, $outputPrefix]);
            if (!$ppmResult->successful()) {
                Log::error('pdftoppm PDF-to-image conversion failed.', [
                    'exit_code' => $ppmResult->exitCode(),
                    'error' => $ppmResult->errorOutput(),
                ]);
                return null;
            }

            // Find all page images
            $images = glob($tempDir . DIRECTORY_SEPARATOR . 'page-*.png');
            if (empty($images)) {
                Log::warning('No page images were generated by pdftoppm.');
                return null;
            }

            // Sort naturally (page-1, page-2, ..., page-10)
            natsort($images);

            $extractedText = '';
            foreach ($images as $imagePath) {
                $ocrResult = Process::run(['tesseract', $imagePath, 'stdout']);
                if ($ocrResult->successful()) {
                    $extractedText .= $ocrResult->output() . "\n";
                } else {
                    Log::warning('Tesseract OCR failed on page image.', [
                        'image' => basename($imagePath),
                        'error' => $ocrResult->errorOutput(),
                    ]);
                }
            }

            $trimmedText = trim($extractedText);
            return $trimmedText !== '' ? $trimmedText : null;

        } catch (\Exception $e) {
            Log::error('Exception during PDF OCR text extraction.', ['message' => $e->getMessage()]);
            return null;
        } finally {
            // Clean up files
            @unlink($tempPdf);
            @unlink($pdfPath);
            if (is_dir($tempDir)) {
                foreach (glob($tempDir . DIRECTORY_SEPARATOR . '*') as $file) {
                    @unlink($file);
                }
                @rmdir($tempDir);
            }
        }
    }

    /**
     * Extracts text from a standalone image using Tesseract OCR.
     */
    protected function extractImage(string $fileBytes, string $extension): ?string
    {
        Log::info("Running Tesseract OCR on direct {$extension} image file.");

        $tempImage = tempnam(sys_get_temp_dir(), 'ocr_img_');
        $imagePath = $tempImage . '.' . $extension;

        try {
            file_put_contents($imagePath, $fileBytes);

            $ocrResult = Process::run(['tesseract', $imagePath, 'stdout']);
            if (!$ocrResult->successful()) {
                Log::error('Tesseract image OCR failed.', [
                    'exit_code' => $ocrResult->exitCode(),
                    'error' => $ocrResult->errorOutput(),
                ]);
                return null;
            }

            $trimmedText = trim($ocrResult->output());
            return $trimmedText !== '' ? $trimmedText : null;
        } catch (\Exception $e) {
            Log::error('Exception during image OCR text extraction.', ['message' => $e->getMessage()]);
            return null;
        } finally {
            @unlink($tempImage);
            @unlink($imagePath);
        }
    }

    /**
     * Fallback for unknown file extensions. It checks the extension from the file name.
     */
    protected function extractFallback(string $fileBytes, string $fileName): ?string
    {
        $extension = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));
        if (in_array($extension, ['docx', 'pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp', 'gif'])) {
            return $this->extract($fileBytes, $fileName, $extension);
        }

        Log::warning('Unsupported file type for text extraction.', [
            'file_name' => $fileName,
            'extension' => $extension,
        ]);
        return null;
    }
}
